name: BluePD

options:
  bundleIdPrefix: com.bluepd

targets:
  BluePD:
    type: application
    platform: iOS
    deploymentTarget: "17.0"

    sources:
      - path: BluePD/BluePD

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bluepd.app
        INFOPLIST_FILE: BluePD/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        MARKETING_VERSION: 9.9
        CURRENT_PROJECT_VERSION: 99

    info:
      path: BluePD/Info.plist
      properties:
        CFBundleDisplayName: BluePD
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
